import { expect, test } from '@playwright/test'

/**
 * Demo 建置（`VITE_SUPABASE_*` 清空）：與 **`npm run test:e2e:smoke`** 同型 preview；
 * 驗證 Seq 29 P1：兩個 **Pdf16 大節**（智能排班／復康服務）；**`ListSectionPanel`**：**排班時間設定**／**排班規則設定（P1）**（**`h3`**、預設展開、**`aria-controls`**）與 **資助復康**（於復康大節內篩選、預設收合、**`hidden`**）；**政策版本** **`ListSectionPanel`**（**`section[aria-labelledby]`**、預設展開、**收合**／**展開** 與 **`hidden`**）；五處 **`aria-controls`** 目標 **`id`** 全相異；**審計** landmark、**審計** **展開**／**收合**（**`aria-controls`**、**`hidden`**、搜尋 **`placeholder`**）與無 Edge 時之本機說明（對照 UAT 未設 env 預期）。
 */
test.describe('system-settings policy P1（demo 無 Supabase）', () => {
  test('政策區塊標題與本機儲存說明可見', async ({ page }) => {
    await page.goto('/#system-settings')
    await expect(page).toHaveURL(/#system-settings/)
    await expect(page.getByRole('heading', { name: '系統設定', exact: true })).toBeVisible()
    const schedulingHeading = page.getByRole('heading', { name: '智能排班設定', exact: true })
    await expect(schedulingHeading).toBeVisible()
    const schedulingSectionId = await schedulingHeading.getAttribute('id')
    expect(schedulingSectionId).toBeTruthy()
    await expect(page.locator(`section[aria-labelledby="${schedulingSectionId}"]`)).toHaveCount(1)
    const scheduleTimeHeading = page.getByRole('heading', { name: '排班時間設定', exact: true })
    await expect(scheduleTimeHeading).toBeVisible()
    expect(await scheduleTimeHeading.evaluate((el) => el.tagName.toLowerCase())).toBe('h3')
    // 自 Pdf16 大節內篩選內層 section，避免與「排班規則設定（P1）」之第二個「收合」同時命中（Playwright strict）。
    const schedulingPdfSection = page.locator(`section[aria-labelledby="${schedulingSectionId}"]`)
    const scheduleTimePanel = schedulingPdfSection.locator('section').filter({ has: scheduleTimeHeading })
    const collapseScheduleTime = scheduleTimePanel.getByRole('button', { name: '收合' })
    await expect(collapseScheduleTime).toBeVisible()
    const scheduleTimeContentId = await collapseScheduleTime.getAttribute('aria-controls')
    expect(scheduleTimeContentId).toBeTruthy()
    const scheduleTimeContent = page.locator(`[id="${scheduleTimeContentId}"]`)
    await expect(scheduleTimeContent).toHaveCount(1)
    await expect(scheduleTimeContent).not.toHaveAttribute('hidden')
    await expect(scheduleTimePanel.getByText('排班開始（HH:mm）')).toBeVisible()
    const rulesHeading = page.getByRole('heading', { name: '排班規則設定（P1）', exact: true })
    await expect(rulesHeading).toBeVisible()
    expect(await rulesHeading.evaluate((el) => el.tagName.toLowerCase())).toBe('h3')
    const rulesPanel = schedulingPdfSection.locator('section').filter({ has: rulesHeading })
    const collapseRules = rulesPanel.getByRole('button', { name: '收合' })
    await expect(collapseRules).toBeVisible()
    const rulesContentId = await collapseRules.getAttribute('aria-controls')
    expect(rulesContentId).toBeTruthy()
    expect(rulesContentId).not.toBe(scheduleTimeContentId)
    const rulesContent = page.locator(`[id="${rulesContentId}"]`)
    await expect(rulesContent).toHaveCount(1)
    await expect(rulesContent).not.toHaveAttribute('hidden')
    await expect(rulesPanel.getByText('治療師小組活動每日上限（節）')).toBeVisible()
    const rehabHeading = page.getByRole('heading', { name: '復康服務基本設定', exact: true })
    await expect(rehabHeading).toBeVisible()
    const rehabSectionId = await rehabHeading.getAttribute('id')
    expect(rehabSectionId).toBeTruthy()
    expect(rehabSectionId).not.toBe(schedulingSectionId)
    const rehabPdfSection = page.locator(`section[aria-labelledby="${rehabSectionId}"]`)
    await expect(rehabPdfSection).toHaveCount(1)
    const subsidizedListHeading = page.getByRole('heading', {
      name: '資助復康服務與認知障礙症服務（P1）',
      exact: true,
    })
    await expect(subsidizedListHeading).toBeVisible()
    const subsidizedPanel = rehabPdfSection.locator('section').filter({ has: subsidizedListHeading })
    const expandSubsidized = subsidizedPanel.getByRole('button', { name: '展開' })
    await expect(expandSubsidized).toBeVisible()
    const subsidizedContentId = await expandSubsidized.getAttribute('aria-controls')
    expect(subsidizedContentId).toBeTruthy()
    const subsidizedContent = page.locator(`[id="${subsidizedContentId}"]`)
    await expect(subsidizedContent).toHaveCount(1)
    await expect(subsidizedContent).toHaveAttribute('hidden', '')
    await expandSubsidized.click()
    await expect(subsidizedContent).not.toHaveAttribute('hidden')
    await expect(subsidizedPanel.getByText(/Special Care 僅由治療師承接/)).toBeVisible()
    const localGroup = page.getByRole('group', { name: '本機設定（瀏覽器儲存）' })
    await expect(localGroup).toBeVisible()
    await expect(localGroup).toHaveAttribute('aria-busy', 'false')
    const policyHeading = page.getByRole('heading', { name: '政策版本（雲端提交）（P1）', exact: true })
    await expect(policyHeading).toBeVisible()
    const policyHeadingId = await policyHeading.getAttribute('id')
    expect(policyHeadingId).toBeTruthy()
    await expect(page.locator(`section[aria-labelledby="${policyHeadingId}"]`)).toHaveCount(1)
    const policyListPanel = page.locator('section').filter({ has: policyHeading })
    const collapsePolicy = policyListPanel.getByRole('button', { name: '收合' })
    await expect(collapsePolicy).toBeVisible()
    const policyListContentId = await collapsePolicy.getAttribute('aria-controls')
    expect(policyListContentId).toBeTruthy()
    expect(policyListContentId).not.toBe(scheduleTimeContentId)
    expect(policyListContentId).not.toBe(rulesContentId)
    expect(policyListContentId).not.toBe(subsidizedContentId)
    const policyListContent = page.locator(`[id="${policyListContentId}"]`)
    await expect(policyListContent).toHaveCount(1)
    await expect(policyListContent).not.toHaveAttribute('hidden')
    await collapsePolicy.click()
    await expect(policyListContent).toHaveAttribute('hidden', '')
    await policyListPanel.getByRole('button', { name: '展開' }).click()
    await expect(policyListContent).not.toHaveAttribute('hidden')
    await expect(page.getByText('未偵測到 Supabase 環境變數')).toBeVisible()
    await expect(page.getByRole('button', { name: '儲存設定（本機）' })).toBeVisible()
    const auditHeading = page.getByRole('heading', { name: '系統設定與相關審計（全域）', exact: true })
    await expect(auditHeading).toBeVisible()
    const auditHeadingId = await auditHeading.getAttribute('id')
    expect(auditHeadingId).toBeTruthy()
    const auditSection = page.locator(`section[aria-labelledby="${auditHeadingId}"]`)
    await expect(auditSection).toHaveCount(1)
    const expandAudit = auditSection.getByRole('button', { name: '展開審計' })
    await expect(expandAudit).toBeVisible()
    const auditRegionId = await expandAudit.getAttribute('aria-controls')
    expect(auditRegionId).toBeTruthy()
    const auditRegion = page.locator(`[id="${auditRegionId}"]`)
    await expect(auditRegion).toHaveCount(1)
    await expect(auditRegion).toHaveAttribute('hidden', '')
    await expect(page.getByPlaceholder('搜尋 actor / entity / detail')).toHaveCount(0)

    await expandAudit.click()
    await expect(auditSection.getByRole('button', { name: '收合審計' })).toBeVisible()
    await expect(auditRegion).not.toHaveAttribute('hidden')
    await expect(page.getByPlaceholder('搜尋 actor / entity / detail')).toBeVisible()

    await auditSection.getByRole('button', { name: '收合審計' }).click()
    await expect(expandAudit).toBeVisible()
    await expect(auditRegion).toHaveAttribute('hidden', '')
    await expect(page.getByPlaceholder('搜尋 actor / entity / detail')).toHaveCount(0)
    expect(
      new Set([
        scheduleTimeContentId!,
        rulesContentId!,
        subsidizedContentId!,
        policyListContentId!,
        auditRegionId!,
      ]).size,
    ).toBe(5)
  })
})
