export { AuthProvider } from './context/AuthProvider'
export { useAuth } from './hooks/useAuth'
export { SignInScreen } from './components/SignInScreen'
export { useAuthActorId } from './hooks/useAuthActorId'
export { resolveStaffProfileIdForWorkPlans } from './staffProfileBinding'
export { resolveStarcareRole, hasPermission, canApproveForm } from './permissions'
export type { StarcareRole, AuthPermission } from './permissions'
