import type { AuthPermission, StarcareRole } from './authPermissionTypes'

const PERMISSIONS_BY_ROLE: Record<StarcareRole, AuthPermission[]> = {
  Admin: [
    'view:dashboard',
    'view:work-plan-compose',
    'view:work-session-plans',
    'view:service-forms',
    'view:historical-documents',
    'view:work-analysis-review',
    'view:ai-report-center',
    'view:notification-center',
    'view:user-manual',
    'view:shift-start-handover',
    'view:shift-end-handover',
    'view:scheduling',
    'view:rehab-activity-tracking',
    'view:assessment-management',
    'view:system-settings',
    'view:user-role-admin',
    'view:residents',
    'view:staff-import',
    'view:activity-sessions-import',
    'action:approve-form',
  ],
  TeamLead: [
    'view:dashboard',
    'view:work-plan-compose',
    'view:work-session-plans',
    'view:service-forms',
    'view:historical-documents',
    'view:work-analysis-review',
    'view:ai-report-center',
    'view:notification-center',
    'view:user-manual',
    'view:shift-start-handover',
    'view:shift-end-handover',
    'view:scheduling',
    'view:rehab-activity-tracking',
    'view:assessment-management',
    'view:system-settings',
    'view:residents',
    'view:staff-import',
    'view:activity-sessions-import',
    'action:approve-form',
  ],
  Staff: [
    'view:dashboard',
    'view:work-session-plans',
    'view:service-forms',
    'view:historical-documents',
    'view:notification-center',
    'view:user-manual',
    'view:shift-start-handover',
    'view:shift-end-handover',
    'view:scheduling',
    'view:rehab-activity-tracking',
    'view:assessment-management',
  ],
}

export const hasPermission = (role: StarcareRole, permission: AuthPermission): boolean =>
  PERMISSIONS_BY_ROLE[role].includes(permission)
