/**
 * 全站 UI 複合片段（與 `base` 組字或固定色階）；自 `extended` 拆出以維持單檔 ≤200 行。
 */
import { uiTokensBase } from './base'

export const uiTokensExtendedComposites = {
  signInAccentButtonFullWidth: `${uiTokensBase.btnAccent} w-full`,
  formSheetCloseButtonSecondary: `${uiTokensBase.btnSecondary} shrink-0 px-2.5 py-1 text-sm`,
  aiReportComposerShell: `${uiTokensBase.surfaceCardCompact} flex flex-col gap-3 sm:flex-row sm:items-end`,
  aiReportComposerKeywordField: `${uiTokensBase.formFieldStack} min-w-[12rem] flex-1`,
  auditTrailFilterSelectMin9: `${uiTokensBase.formSelect} w-auto min-w-[9rem] text-xs`,
  auditTrailFilterSelectMin8: `${uiTokensBase.formSelect} w-auto min-w-[8rem] text-xs`,
  formInputMaxXsTextXs: `${uiTokensBase.formInput} max-w-xs text-xs`,
  tableCellNowrap: 'whitespace-nowrap px-2 py-2',
  handoverHistorySignatureMeta: 'mt-1 block text-slate-600',
  btnDangerOutlineDisabled: `${uiTokensBase.btnDangerOutline} disabled:cursor-not-allowed disabled:opacity-50`,
  btnCompactDisabled: `${uiTokensBase.btnCompact} disabled:cursor-not-allowed disabled:opacity-50`,
  staffTableRowSecondaryAction: `${uiTokensBase.btnSecondary} mr-2 text-[11px] disabled:cursor-not-allowed disabled:opacity-50`,
  statDdXlSlate900: 'text-xl font-semibold text-slate-900',
  statDdXlAmber800: 'text-xl font-semibold text-amber-800',
  statDdXlViolet900: 'text-xl font-semibold text-violet-900',
  statDdXlEmerald800: 'text-xl font-semibold text-emerald-800',
  statDdXlRed800: 'text-xl font-semibold text-red-800',
  textSubtleXsViolet700: 'text-xs text-violet-700',
  statValueLgSlate900: 'mt-1 text-lg font-semibold text-slate-900',
  textSubtleXsAmber700: 'text-xs text-amber-700',
  statValueLgAmber900: 'mt-1 text-lg font-semibold text-amber-900',
  statValueLgViolet900: 'mt-1 text-lg font-semibold text-violet-900',
  textSubtleXsEmerald700: 'text-xs text-emerald-700',
  statValueLgEmerald900: 'mt-1 text-lg font-semibold text-emerald-900',
  dashboardStatTileValueRed800: 'mt-1 text-2xl font-semibold text-red-800',
  dashboardStatTileValueEmerald800: 'mt-1 text-2xl font-semibold text-emerald-800',
  blockHelpMt2: `${uiTokensBase.blockHelp} mt-2`,
  textUrgentHintMt2: `${uiTokensBase.textUrgentHint} mt-2`,
  blockHelpBlockMt1: `mt-1 block ${uiTokensBase.blockHelp}`,
  textSubtleXsMt2: 'mt-2 text-xs text-slate-500',
  textSubtleXsMt3: 'mt-3 text-xs text-slate-500',
  formInlineErrorXs: 'text-xs text-red-600',
  formInlineErrorMt2: 'mt-2 text-sm text-red-600',
  formInlineErrorMt2Xs: 'mt-2 text-xs text-red-600',
  formInlineErrorMt3Xs: 'mt-3 text-xs text-red-600',
  formInlineErrorMt3: 'mt-3 text-sm text-red-600',
  textSubtleXsMuted400: 'text-xs text-slate-400',
  btnCompactMt2: `${uiTokensBase.btnCompact} mt-2`,
  btnSuccessMt2: `${uiTokensBase.btnSuccess} mt-2`,
  btnDangerOutlineMt3: `${uiTokensBase.btnDangerOutline} mt-3`,
  formInputMt2: `${uiTokensBase.formInput} mt-2`,
  formInputMt3: `${uiTokensBase.formInput} mt-3`,
  formInputMt3TextXs: `${uiTokensBase.formInput} mt-3 text-xs`,
  helpFinePrintMt2: `${uiTokensBase.helpFinePrint} mt-2`,
  btnPrimaryMt3WFit: `${uiTokensBase.btnPrimary} mt-3 w-fit`,
  btnSecondaryMt3: `${uiTokensBase.btnSecondary} mt-3`,
  btnSecondaryMt3TextXs: `${uiTokensBase.btnSecondary} mt-3 text-xs`,
  formTextareaMt2: `${uiTokensBase.formTextarea} mt-2`,
  metaChipMl2: `${uiTokensBase.metaChip} ml-2`,
  textMutedBodyMl2: 'ml-2 text-slate-600',
  hashLinkAccentMl2: 'ml-2 text-violet-700 underline',
  textSubtleXsMl2Slate400: 'ml-2 text-xs text-slate-400',
  residentListPagerMetaMl2: 'ml-2 text-slate-500',
  formFieldStackSmColSpan2: `${uiTokensBase.formFieldStack} sm:col-span-2`,
  formFieldStackSmColSpan2Lg1: `${uiTokensBase.formFieldStack} sm:col-span-2 lg:col-span-1`,
  formToggleLabelMt4: `${uiTokensBase.formToggleLabel} mt-4`,
  stackVerticalMt3: `${uiTokensBase.stackVertical} mt-3`,
  stackVerticalMt4: `${uiTokensBase.stackVertical} mt-4`,
  handoverHomeContentWidth: `mx-auto w-full max-w-5xl ${uiTokensBase.stackVertical}`,
  surfaceCardCompactDimmed: `${uiTokensBase.surfaceCardCompact} opacity-70`,
  schedulingHistoryUndoSection: `${uiTokensBase.surfaceCardCompact} border-slate-100 bg-slate-50`,
  formInputSearchNarrow: `${uiTokensBase.formInput} max-w-xs sm:max-w-[14rem]`,
  formSelectAutoMin8rem: `${uiTokensBase.formSelect} w-auto min-w-[8rem]`,
  moduleDescriptionSlate700: `${uiTokensBase.moduleDescription} text-slate-700`,
  moduleDescriptionMt2Slate700: `${uiTokensBase.moduleDescription} mt-2 text-slate-700`,
  listDivideShellMt4TextSm: 'mt-4 divide-y divide-slate-100 rounded-lg border border-slate-200 text-sm',
  textMutedBodyXs: 'text-xs text-slate-600',
  textSubtleXsMl2: 'ml-2 text-xs text-slate-500',
  textSubtleXsMono: 'font-mono text-xs text-slate-500',
  rosterConfirmChoiceCardMuted: `${uiTokensBase.rosterConfirmChoiceCard} opacity-60`,
  /** 院友單筆表單：格線與核取列 */
  residentFormGrid: 'grid gap-3 text-sm',
  residentFormGridMt3: 'mt-3 grid gap-3 text-sm',
  residentFormCheckboxLabel: `flex items-center gap-2 ${uiTokensBase.formLabel}`,
  /** 歷史文件／評估管理：表格外殼與儲存格 */
  tableCompactTh: 'border-b border-slate-200 bg-slate-50 px-3 py-2 text-left text-xs font-semibold text-slate-700',
  historicalDocumentsTableWrap: 'overflow-x-auto rounded-lg border border-slate-200',
  historicalDocumentsTd:
    'max-w-[14rem] border-b border-slate-100 px-3 py-2 text-sm text-slate-800',
  historicalDocumentsTdNarrative:
    'max-w-[14rem] border-b border-slate-100 px-3 py-2 text-sm text-slate-800 whitespace-pre-wrap',
  historicalDocumentsTdMonoId:
    'max-w-[14rem] border-b border-slate-100 px-3 py-2 font-mono text-xs text-slate-800',
  assessmentTableWrapMt2: 'mt-2 overflow-x-auto rounded-lg border border-slate-200',
  assessmentTableTd: 'border-b border-slate-100 px-3 py-2 text-sm text-slate-800',
  /** 工作計劃五步：標題與步驟卡／提示色（天藍主題） */
  workPlanStepperTitle: `${uiTokensBase.blockHeading} text-sky-950`,
  workPlanStepCardActive:
    'flex h-full flex-col rounded-lg px-3 py-2 text-xs bg-sky-600 text-white shadow-md',
  workPlanStepCardDone:
    'flex h-full flex-col rounded-lg px-3 py-2 text-xs bg-emerald-100 text-emerald-900',
  workPlanStepCardPending:
    'flex h-full flex-col rounded-lg px-3 py-2 text-xs bg-white text-slate-600 ring-1 ring-slate-200',
  workPlanStepHintComplete: 'mt-1 leading-snug text-emerald-800',
  workPlanStepHintActive: 'mt-1 leading-snug text-sky-100',
  workPlanStepHintIdle: 'mt-1 leading-snug text-slate-500',
  /** 通知中心：嚴重度標籤（整段 class，避免模板拼色） */
  notificationSeverityBadgeHigh: 'rounded-full px-2 py-0.5 text-xs bg-red-100 text-red-700',
  notificationSeverityBadgeMedium: 'rounded-full px-2 py-0.5 text-xs bg-amber-100 text-amber-700',
  notificationSeverityBadgeLow: 'rounded-full px-2 py-0.5 text-xs bg-slate-100 text-slate-700',
  /** 排班側欄：小螢幕位移與導覽列組合態 */
  sidebarShellMobileOpen: `${uiTokensBase.sidebarShell} translate-x-0`,
  sidebarShellMobileClosed: `${uiTokensBase.sidebarShell} -translate-x-full md:translate-x-0`,
  sidebarNavLinkRowActive: `${uiTokensBase.sidebarNavLink} ${uiTokensBase.sidebarNavLinkActive}`,
  sidebarNavLinkRowInactive: `${uiTokensBase.sidebarNavLink} ${uiTokensBase.sidebarNavLinkInactive}`,
  /** 根版面：主內容捲動區（含頂欄留白） */
  appMainContentArea: `mx-auto w-full max-w-6xl flex-1 overflow-auto p-4 md:p-6 lg:p-8 ${uiTokensBase.mainWithMobileNavPad}`,
  /** 根應用：工作階段載入中全螢幕 */
  appAuthSessionLoadingRoot: 'flex min-h-screen items-center justify-center bg-slate-100 text-slate-600',
  /** 響應式表單抽屜：全螢幕視窗層 */
  formSheetViewportRoot: 'fixed inset-0 z-[100]',
  /** 表單標題列左側（標題長字省略） */
  formSheetTitleShrinkWrap: 'min-w-0',
} as const
