/**
 * 與 `base` 組字：登入／表單／稽核下拉／員工列動作／stat 數字字級／儀表數字色。
 * 表單邊距 meta／版面堆疊見 **`extendedCompositesFormsSpacing`**。
 */
import { uiTokensBase } from './base'

export const uiTokensExtendedCompositesFormsInputs = {
  signInAccentButtonFullWidth: `${uiTokensBase.btnAccent} w-full`,
  formSheetCloseButtonSecondary: `${uiTokensBase.btnSecondary} shrink-0 px-2.5 py-1 text-sm`,
  aiReportComposerShell: `${uiTokensBase.surfaceCardCompact} flex flex-col gap-3 sm:flex-row sm:items-end`,
  aiReportComposerKeywordField: `${uiTokensBase.formFieldStack} min-w-[12rem] flex-1`,
  auditTrailFilterSelectMin9: `${uiTokensBase.formSelect} w-auto min-w-[9rem] text-xs`,
  auditTrailFilterSelectMin8: `${uiTokensBase.formSelect} w-auto min-w-[8rem] text-xs`,
  formInputMaxXsTextXs: `${uiTokensBase.formInput} max-w-xs text-xs`,
  tableCellNowrap: 'whitespace-nowrap px-2 py-2',
  handoverHistorySignatureMeta: 'mt-1 block text-slate-600',
  btnDangerOutlineDisabled: `${uiTokensBase.btnDangerOutline} disabled:cursor-not-allowed disabled:opacity-50`,
  btnCompactDisabled: `${uiTokensBase.btnCompact} disabled:cursor-not-allowed disabled:opacity-50`,
  staffTableRowSecondaryAction: `${uiTokensBase.btnSecondary} mr-2 text-[11px] disabled:cursor-not-allowed disabled:opacity-50`,
  statDdXlSlate900: 'text-xl font-semibold text-slate-900',
  statDdXlAmber800: 'text-xl font-semibold text-amber-800',
  statDdXlViolet900: 'text-xl font-semibold text-violet-900',
  statDdXlEmerald800: 'text-xl font-semibold text-emerald-800',
  statDdXlRed800: 'text-xl font-semibold text-red-800',
  textSubtleXsViolet700: 'text-xs text-violet-700',
  statValueLgSlate900: 'mt-1 text-lg font-semibold text-slate-900',
  textSubtleXsAmber700: 'text-xs text-amber-700',
  statValueLgAmber900: 'mt-1 text-lg font-semibold text-amber-900',
  statValueLgViolet900: 'mt-1 text-lg font-semibold text-violet-900',
  textSubtleXsEmerald700: 'text-xs text-emerald-700',
  statValueLgEmerald900: 'mt-1 text-lg font-semibold text-emerald-900',
  dashboardStatTileValueRed800: 'mt-1 text-2xl font-semibold text-red-800',
  dashboardStatTileValueEmerald800: 'mt-1 text-2xl font-semibold text-emerald-800',
  blockHelpMt2: `${uiTokensBase.blockHelp} mt-2`,
  textUrgentHintMt2: `${uiTokensBase.textUrgentHint} mt-2`,
  blockHelpBlockMt1: `mt-1 block ${uiTokensBase.blockHelp}`,
  textSubtleXsMt2: 'mt-2 text-xs text-slate-500',
  textSubtleXsMt3: 'mt-3 text-xs text-slate-500',
  formInlineErrorXs: 'text-xs text-red-600',
  formInlineErrorMt2: 'mt-2 text-sm text-red-600',
  formInlineErrorMt2Xs: 'mt-2 text-xs text-red-600',
  formInlineErrorMt3Xs: 'mt-3 text-xs text-red-600',
  formInlineErrorMt3: 'mt-3 text-sm text-red-600',
  textSubtleXsMuted400: 'text-xs text-slate-400',
  btnCompactMt2: `${uiTokensBase.btnCompact} mt-2`,
  btnSuccessMt2: `${uiTokensBase.btnSuccess} mt-2`,
  btnDangerOutlineMt3: `${uiTokensBase.btnDangerOutline} mt-3`,
  formInputMt2: `${uiTokensBase.formInput} mt-2`,
  formInputMt3: `${uiTokensBase.formInput} mt-3`,
  formInputMt3TextXs: `${uiTokensBase.formInput} mt-3 text-xs`,
  helpFinePrintMt2: `${uiTokensBase.helpFinePrint} mt-2`,
  btnPrimaryMt3WFit: `${uiTokensBase.btnPrimary} mt-3 w-fit`,
  btnSecondaryMt3: `${uiTokensBase.btnSecondary} mt-3`,
  btnSecondaryMt3TextXs: `${uiTokensBase.btnSecondary} mt-3 text-xs`,
  formTextareaMt2: `${uiTokensBase.formTextarea} mt-2`,
} as const
